# Generated by Django 2.2.12 on 2023-05-10 14:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='InstitutionName', max_length=250)),
                ('short_name', models.CharField(max_length=80, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('value', models.CharField(max_length=30)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('result', models.CharField(max_length=250)),
                ('result_date', models.DateField()),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Institution')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.QuestionCategory')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birth_date', models.DateField()),
                ('home_addr', models.CharField(blank=True, max_length=250)),
                ('work_addr', models.CharField(blank=True, max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.Institution')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('question', models.ManyToManyField(to='donor.Question')),
            ],
        ),
    ]
