# Generated by Django 2.2.12 on 2023-05-14 21:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('value', models.CharField(max_length=30)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('result', models.CharField(max_length=250)),
                ('result_date', models.DateField()),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birth_date', models.DateField()),
                ('home_addr', models.CharField(blank=True, max_length=250)),
                ('work_addr', models.CharField(blank=True, max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('donated_volume', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('rh_factor', models.CharField(choices=[('Rh+', 'Rh+'), ('Rh-', 'Rh-')], max_length=3, null=True)),
                ('blood_pressure', models.CharField(max_length=4, null=True)),
                ('heart_rate', models.CharField(max_length=9, null=True)),
                ('hemoglobin', models.IntegerField(null=True)),
                ('common_info', models.CharField(max_length=500, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('donor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('question', models.ManyToManyField(to='institution.Question')),
            ],
        ),
    ]
