# Generated by Django 2.2.12 on 2023-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=6),
        ),
    ]
