# Generated by Django 2.2.12 on 2023-05-12 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
        ('institution', '0001_initial')
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='status',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(to='institution.Question'),
        ),
        migrations.AlterField(
            model_name='status',
            name='dlm',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
