# Generated by Django 2.2.12 on 2023-05-16 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20230515_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('rh_factor', models.CharField(choices=[('Rh+', 'Rh+'), ('Rh-', 'Rh-')], max_length=3, null=True)),
                ('common_info', models.CharField(max_length=500, null=True)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentHealthParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=4, null=True)),
                ('heart_rate', models.CharField(max_length=9, null=True)),
                ('hemoglobin', models.IntegerField(null=True)),
                ('common_info', models.CharField(max_length=500, null=True)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='donation_date',
            field=models.DateField(verbose_name='%d.%m.%Y'),
        ),
        migrations.DeleteModel(
            name='HealthParameter',
        ),
        migrations.AddField(
            model_name='currenthealthparameter',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.History'),
        ),
    ]
