# Generated by Django 2.2.12 on 2023-05-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20230516_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='donor_id',
            new_name='donor',
        ),
    ]
