# Generated by Django 2.2.12 on 2023-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20230516_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthealthparameter',
            name='blood_pressure',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='currenthealthparameter',
            name='heart_rate',
            field=models.IntegerField(null=True),
        ),
    ]
