# Generated by Django 2.2.12 on 2023-05-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20230516_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='test',
            name='donor',
        ),
        migrations.AddField(
            model_name='history',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Profile'),
        ),
        migrations.AddField(
            model_name='test',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Profile'),
        ),
        migrations.AlterField(
            model_name='currenthealthparameter',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.History'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча')], max_length=6),
        ),
    ]
