# Generated by Django 2.2.12 on 2023-05-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20230516_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodparameter',
            name='rh_factor',
            field=models.CharField(choices=[('Rh+', 'Rh+'), ('Rh-', 'Rh-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='currenthealthparameter',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor.History'),
        ),
    ]
