# Generated by Django 2.2.12 on 2023-05-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20230516_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code'),
        ),
    ]
