# Generated by Django 2.2.12 on 2023-05-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('donor', '0008_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='donor',
        ),
        migrations.AddField(
            model_name='answer',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Profile'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Question'),
        ),
    ]
