# Generated by Django 2.2.12 on 2023-05-17 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('donor', '0009_auto_20230517_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_date',
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code'),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='testdetail',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.Test'),
        ),
    ]
