# Generated by Django 2.2.12 on 2023-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_auto_20230517_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='result_date',
            field=models.DateField(null=True),
        ),
    ]
