# Generated by Django 2.2.12 on 2023-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0011_auto_20230517_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Ч', 'Чоловіча'), ('Ж', 'Жіноча')], max_length=15),
        ),
    ]
