# Generated by Django 2.2.12 on 2023-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_auto_20230518_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='result_date',
        ),
        migrations.AddField(
            model_name='test',
            name='test_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
