# Generated by Django 2.2.12 on 2023-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0014_auto_20230518_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodparameter',
            name='blood_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloodparameter',
            name='common_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloodparameter',
            name='rh_factor',
            field=models.CharField(choices=[('Rh+', 'Rh+'), ('Rh-', 'Rh-')], max_length=10, null=True),
        ),
    ]
