# Generated by Django 2.2.12 on 2023-05-12 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='InstitutionName', max_length=250)),
                ('short_name', models.CharField(max_length=80, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('value', models.CharField(max_length=30)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institution.Status', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('dlm', models.DateTimeField(default=datetime.datetime.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.QuestionCategory')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institution.Status', to_field='code')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institution.Status', to_field='code'),
        ),
    ]
