# Generated by Django 2.2.12 on 2023-05-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncategory',
            old_name='inst',
            new_name='institution',
        ),
    ]
