# Generated by Django 2.2.12 on 2023-05-12 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0002_auto_20230512_1139'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('birth_date', models.DateField()),
                ('home_addr', models.CharField(blank=True, max_length=250)),
                ('work_addr', models.CharField(blank=True, max_length=250)),
                ('dlm', models.DateTimeField(default=datetime.datetime.now)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='donor.Status', to_field='code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
